# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-18 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0007_component_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='components_provided',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('student_name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=100)),
                ('section', models.CharField(choices=[('ECE A', 'ECE A'), ('ECE B', 'ECE B'), ('ECE C', 'ECE C')], max_length=100)),
                ('year', models.CharField(choices=[('1st YEAR', 'First year'), ('2nd YEAR', 'Second year'), ('3rd YEAR', 'Third year'), ('4th YEAR', 'Fourth year')], max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('email_id', models.EmailField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.component')),
            ],
        ),
    ]
