# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='descripition',
            new_name='description',
        ),
    ]
