# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-10 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_auto_20180925_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
