# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-13 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_remove_component_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
